In [1]:
import polars as pl

In [4]:
leaderboard = pl.read_csv("../logs/titanic/classic/leaderboard.csv")
leaderboard

shape: (5, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ experimen ┆ model_nam ┆ dataset_t ┆ preproces ┆ … ┆ std_roc_a ┆ config_pa ┆ run_dir   ┆ artifact │
│ t_name    ┆ e         ┆ ype       ┆ sing      ┆   ┆ uc        ┆ th        ┆ ---       ┆ _dir     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ f64       ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ xgb_class ┆ xgb_class ┆ original  ┆ standard  ┆ … ┆ 0.024482  ┆ configs/c ┆ logs/clas ┆ models/c │
│ ifier_opt ┆ ifier     ┆           ┆           ┆   ┆           ┆ lassic_co ┆ sic/xgb_c ┆ lassic/x │
│ una       ┆           ┆           ┆           ┆   ┆           ┆ nfig/xgb_ ┆ lassifier ┆ gb_class │
│           ┆           ┆           ┆           ┆   ┆           ┆ cla…      ┆ _op…      ┆ ifier_…  │
│ xgb_class ┆ xgb_class ┆ original  ┆ standard  ┆ … ┆ 0.022642  ┆ configs/c ┆ logs/clas ┆ models/c │
│ ifier     ┆ ifier     ┆           ┆           ┆   ┆           ┆ lassic_co ┆ sic/xgb_c ┆ lassic/x │
│           ┆           ┆           ┆           ┆   ┆           ┆ nfig/xgb_ ┆ lassifier ┆ gb_class │
│           ┆           ┆           ┆           ┆   ┆           ┆ cla…      ┆ _or…      ┆ ifier_…  │
│ xgb_class ┆ xgb_class ┆ original  ┆ standard  ┆ … ┆ 0.022642  ┆ configs/c ┆ logs/clas ┆ models/c │
│ ifier     ┆ ifier     ┆           ┆           ┆   ┆           ┆ lassic_co ┆ sic/xgb_c ┆ lassic/x │
│           ┆           ┆           ┆           ┆   ┆           ┆ nfig/xgb_ ┆ lassifier ┆ gb_class │
│           ┆           ┆           ┆           ┆   ┆           ┆ cla…      ┆ _or…      ┆ ifier_…  │
│ logreg_l2 ┆ logistic_ ┆ original  ┆ standard  ┆ … ┆ 0.015927  ┆ configs/c ┆ logs/clas ┆ models/c │
│ _optuna   ┆ regressio ┆           ┆           ┆   ┆           ┆ lassic_co ┆ sic/logre ┆ lassic/l │
│           ┆ n         ┆           ┆           ┆   ┆           ┆ nfig/logr ┆ g_l2_optu ┆ ogreg_l2 │
│           ┆           ┆           ┆           ┆   ┆           ┆ eg_…      ┆ na_…      ┆ _optun…  │
│ logreg_l2 ┆ logistic_ ┆ original  ┆ standard  ┆ … ┆ 0.016489  ┆ configs/c ┆ logs/clas ┆ models/c │
│ _optuna   ┆ regressio ┆           ┆           ┆   ┆           ┆ lassic_co ┆ sic/logre ┆ lassic/l │
│           ┆ n         ┆           ┆           ┆   ┆           ┆ nfig/logr ┆ g_l2_optu ┆ ogreg_l2 │
│           ┆           ┆           ┆           ┆   ┆           ┆ eg_…      ┆ na_…      ┆ _optun…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
leaderboard.sort(by="mean_accuracy", descending=True)[0].get_column("artifact_dir").item()

'models/titanic/classic/xgb_classifier_original_2026-05-08_121108'

In [2]:
leaderboard = pl.read_csv("../logs/titanic/deepnn/leaderboard.csv")
leaderboard

shape: (3, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ experimen ┆ model_nam ┆ dataset_t ┆ preproces ┆ … ┆ std_roc_a ┆ config_pa ┆ run_dir   ┆ artifact │
│ t_name    ┆ e         ┆ ype       ┆ sing      ┆   ┆ uc        ┆ th        ┆ ---       ┆ _dir     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ f64       ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ model_two ┆ model_one ┆ original  ┆ standard  ┆ … ┆ 0.013385  ┆ configs/d ┆ logs/deep ┆ models/d │
│           ┆           ┆           ┆           ┆   ┆           ┆ eepnn_con ┆ nn/model_ ┆ eepnn/mo │
│           ┆           ┆           ┆           ┆   ┆           ┆ fig/model ┆ two_origi ┆ del_two_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ _on…      ┆ nal…      ┆ origin…  │
│ model_two ┆ model_one ┆ original  ┆ standard  ┆ … ┆ 0.017288  ┆ configs/d ┆ logs/deep ┆ models/d │
│           ┆           ┆           ┆           ┆   ┆           ┆ eepnn_con ┆ nn/model_ ┆ eepnn/mo │
│           ┆           ┆           ┆           ┆   ┆           ┆ fig/model ┆ two_origi ┆ del_two_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ _on…      ┆ nal…      ┆ origin…  │
│ custom_mo ┆ custom_mo ┆ binned    ┆ standard  ┆ … ┆ 0.010696  ┆ configs/d ┆ logs/deep ┆ models/d │
│ del1      ┆ del       ┆           ┆           ┆   ┆           ┆ eepnn_con ┆ nn/custom ┆ eepnn/cu │
│           ┆           ┆           ┆           ┆   ┆           ┆ fig/custo ┆ _model1_b ┆ stom_mod │
│           ┆           ┆           ┆           ┆   ┆           ┆ m_m…      ┆ inn…      ┆ el1_bi…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
leaderboard.sort(by="mean_f1", descending=True)[0].get_column("run_dir").item()

'logs/titanic/deepnn/model_two_original_2026-05-28_003227'