In [1]:
import polars as pl

In [2]:
leaderboard = pl.read_csv("../logs/classic/leaderboard.csv")
leaderboard

shape: (19, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ experimen ┆ model_nam ┆ dataset_t ┆ preproces ┆ … ┆ std_roc_a ┆ config_pa ┆ run_dir   ┆ artifact │
│ t_name    ┆ e         ┆ ype       ┆ sing      ┆   ┆ uc        ┆ th        ┆ ---       ┆ _dir     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ f64       ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ xgb_class ┆ xgb_class ┆ original  ┆ standard  ┆ … ┆ 0.022642  ┆ configs/c ┆ logs/clas ┆ models/c │
│ ifier     ┆ ifier     ┆           ┆           ┆   ┆           ┆ lassic_co ┆ sic/xgb_c ┆ lassic/x │
│           ┆           ┆           ┆           ┆   ┆           ┆ nfig/xgb_ ┆ lassifier ┆ gb_class │
│           ┆           ┆           ┆           ┆   ┆           ┆ cla…      ┆ _or…      ┆ ifier_…  │
│ xgb_class ┆ xgb_class ┆ original  ┆ standard  ┆ … ┆ 0.022642  ┆ configs/c ┆ logs/clas ┆ models/c │
│ ifier     ┆ ifier     ┆           ┆           ┆   ┆           ┆ lassic_co ┆ sic/xgb_c ┆ lassic/x │
│           ┆           ┆           ┆           ┆   ┆           ┆ nfig/xgb_ ┆ lassifier ┆ gb_class │
│           ┆           ┆           ┆           ┆   ┆           ┆ cla…      ┆ _or…      ┆ ifier_…  │
│ lgbm_clas ┆ lgbm_clas ┆ original  ┆ standard  ┆ … ┆ 0.018376  ┆ configs/c ┆ logs/clas ┆ models/c │
│ sifier    ┆ sifier    ┆           ┆           ┆   ┆           ┆ lassic_co ┆ sic/lgbm_ ┆ lassic/l │
│           ┆           ┆           ┆           ┆   ┆           ┆ nfig/lgbm ┆ classifie ┆ gbm_clas │
│           ┆           ┆           ┆           ┆   ┆           ┆ _cl…      ┆ r_o…      ┆ sifier…  │
│ catboost_ ┆ catboost_ ┆ original  ┆ standard  ┆ … ┆ 0.016515  ┆ configs/c ┆ logs/clas ┆ models/c │
│ classifie ┆ classifie ┆           ┆           ┆   ┆           ┆ lassic_co ┆ sic/catbo ┆ lassic/c │
│ r         ┆ r         ┆           ┆           ┆   ┆           ┆ nfig/catb ┆ ost_class ┆ atboost_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ oos…      ┆ ifi…      ┆ classi…  │
│ random_fo ┆ random_fo ┆ original  ┆ standard  ┆ … ┆ 0.020259  ┆ configs/c ┆ logs/clas ┆ models/c │
│ rest_clas ┆ rest_clas ┆           ┆           ┆   ┆           ┆ lassic_co ┆ sic/rando ┆ lassic/r │
│ sifier    ┆ sifier    ┆           ┆           ┆   ┆           ┆ nfig/rand ┆ m_forest_ ┆ andom_fo │
│           ┆           ┆           ┆           ┆   ┆           ┆ om_…      ┆ cla…      ┆ rest_c…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ logreg_l2 ┆ logistic_ ┆ original  ┆ standard  ┆ … ┆ 0.016472  ┆ configs/c ┆ logs/clas ┆ models/c │
│           ┆ regressio ┆           ┆           ┆   ┆           ┆ lassic_co ┆ sic/logre ┆ lassic/l │
│           ┆ n         ┆           ┆           ┆   ┆           ┆ nfig/logr ┆ g_l2_orig ┆ ogreg_l2 │
│           ┆           ┆           ┆           ┆   ┆           ┆ eg_…      ┆ ina…      ┆ _origi…  │
│ logreg_l1 ┆ logistic_ ┆ original  ┆ standard  ┆ … ┆ 0.017012  ┆ configs/c ┆ logs/clas ┆ models/c │
│           ┆ regressio ┆           ┆           ┆   ┆           ┆ lassic_co ┆ sic/logre ┆ lassic/l │
│           ┆ n         ┆           ┆           ┆   ┆           ┆ nfig/logr ┆ g_l1_orig ┆ ogreg_l1 │
│           ┆           ┆           ┆           ┆   ┆           ┆ eg_…      ┆ ina…      ┆ _origi…  │
│ logreg_l2 ┆ logistic_ ┆ binned    ┆ standard  ┆ … ┆ 0.012487  ┆ configs/c ┆ logs/clas ┆ models/c │
│           ┆ regressio ┆           ┆           ┆   ┆           ┆ lassic_co ┆ sic/logre ┆ lassic/l │
│           ┆ n         ┆           ┆           ┆   ┆           ┆ nfig/logr ┆ g_l2_binn ┆ ogreg_l2 │
│           ┆           ┆           ┆           ┆   ┆           ┆ eg_…      ┆ ed_…      ┆ _binne…  │
│ logreg_el ┆ logistic_ ┆ binned    ┆ standard  ┆ … ┆ 0.012313  ┆ configs/c ┆ logs/clas ┆ models/c │
│ asticnet  ┆ regressio ┆           ┆           ┆   ┆           ┆ lassic_co ┆ sic/logre ┆ lassic/l │
│           ┆ n         ┆           ┆           ┆   ┆           ┆ nfig/logr ┆ g_elastic ┆ ogreg_el │
│           ┆           ┆           ┆           ┆   ┆           ┆ eg_…      ┆ net…      ┆ asticn…  │
│ logreg_l1 ┆ logistic_ ┆ binned    ┆ standard  ┆ … ┆ 0.012412  ┆ configs/c ┆ logs/clas ┆ models/c │
│           ┆ regressio ┆           ┆           ┆   ┆           ┆ lassic_co ┆ sic/logre ┆ lassic/l │
│           ┆ n         ┆           ┆           ┆   ┆           ┆ nfig/logr ┆ g_l1_binn ┆ ogreg_l1 │
│           ┆           ┆           ┆           ┆   ┆           ┆ eg_…      ┆ ed_…      ┆ _binne…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
leaderboard.sort(by="mean_accuracy", descending=True)[0].get_column("artifact_dir").item()

'models/classic/xgb_classifier_original_2026-05-08_121108'

In [6]:
leaderboard = pl.read_csv("../logs/deepnn/leaderboard.csv")
leaderboard

shape: (4, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ experimen ┆ model_nam ┆ dataset_t ┆ preproces ┆ … ┆ std_roc_a ┆ config_pa ┆ run_dir   ┆ artifact │
│ t_name    ┆ e         ┆ ype       ┆ sing      ┆   ┆ uc        ┆ th        ┆ ---       ┆ _dir     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ f64       ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ model_one ┆ model_one ┆ original  ┆ standard  ┆ … ┆ 0.01372   ┆ configs/d ┆ logs/deep ┆ models/d │
│           ┆           ┆           ┆           ┆   ┆           ┆ eepnn_con ┆ nn/model_ ┆ eepnn/mo │
│           ┆           ┆           ┆           ┆   ┆           ┆ fig/model ┆ one_origi ┆ del_one_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ _tw…      ┆ nal…      ┆ origin…  │
│ Baseline  ┆ model_one ┆ original  ┆ standard  ┆ … ┆ 0.014815  ┆ configs/d ┆ logs/deep ┆ models/d │
│ model     ┆           ┆           ┆           ┆   ┆           ┆ eepnn_con ┆ nn/Baseli ┆ eepnn/Ba │
│           ┆           ┆           ┆           ┆   ┆           ┆ fig/model ┆ ne model_ ┆ seline   │
│           ┆           ┆           ┆           ┆   ┆           ┆ _on…      ┆ ori…      ┆ model_o… │
│ custom_mo ┆ custom_mo ┆ original  ┆ standard  ┆ … ┆ 0.008624  ┆ configs/d ┆ logs/deep ┆ models/d │
│ del1      ┆ del       ┆           ┆           ┆   ┆           ┆ eepnn_con ┆ nn/custom ┆ eepnn/cu │
│           ┆           ┆           ┆           ┆   ┆           ┆ fig/custo ┆ _model1_o ┆ stom_mod │
│           ┆           ┆           ┆           ┆   ┆           ┆ m_m…      ┆ rig…      ┆ el1_or…  │
│ custom_mo ┆ custom_mo ┆ binned    ┆ standard  ┆ … ┆ 0.010696  ┆ configs/d ┆ logs/deep ┆ models/d │
│ del1      ┆ del       ┆           ┆           ┆   ┆           ┆ eepnn_con ┆ nn/custom ┆ eepnn/cu │
│           ┆           ┆           ┆           ┆   ┆           ┆ fig/custo ┆ _model1_b ┆ stom_mod │
│           ┆           ┆           ┆           ┆   ┆           ┆ m_m…      ┆ inn…      ┆ el1_bi…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
leaderboard.sort(by="mean_f1", descending=True)[0].get_column("run_dir").item()

'logs/deepnn/model_one_original_2026-05-12_195825'