In [6]:
import polars as pl

In [7]:
leaderboard = pl.read_csv("../logs/classic/leaderboard.csv")
leaderboard

shape: (1, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ experimen ┆ model_nam ┆ dataset_t ┆ preproces ┆ … ┆ std_roc_a ┆ config_pa ┆ run_dir   ┆ artifact │
│ t_name    ┆ e         ┆ ype       ┆ sing      ┆   ┆ uc        ┆ th        ┆ ---       ┆ _dir     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ f64       ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ xgb_class ┆ xgb_class ┆ original  ┆ standard  ┆ … ┆ 0.022642  ┆ configs/c ┆ logs/clas ┆ models/c │
│ ifier     ┆ ifier     ┆           ┆           ┆   ┆           ┆ lassic_co ┆ sic/xgb_c ┆ lassic/x │
│           ┆           ┆           ┆           ┆   ┆           ┆ nfig/xgb_ ┆ lassifier ┆ gb_class │
│           ┆           ┆           ┆           ┆   ┆           ┆ cla…      ┆ _or…      ┆ ifier_…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
leaderboard.sort(by="mean_accuracy", descending=True)[0].get_column("artifact_dir").item()

'models/classic/xgb_classifier_original_2026-05-08_121108'

In [9]:
leaderboard = pl.read_csv("../logs/deepnn/leaderboard.csv")
leaderboard

shape: (3, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ experimen ┆ model_nam ┆ dataset_t ┆ preproces ┆ … ┆ std_roc_a ┆ config_pa ┆ run_dir   ┆ artifact │
│ t_name    ┆ e         ┆ ype       ┆ sing      ┆   ┆ uc        ┆ th        ┆ ---       ┆ _dir     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ f64       ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ custom_mo ┆ custom_mo ┆ original  ┆ standard  ┆ … ┆ 0.008624  ┆ configs/d ┆ logs/deep ┆ models/d │
│ del1      ┆ del       ┆           ┆           ┆   ┆           ┆ eepnn_con ┆ nn/custom ┆ eepnn/cu │
│           ┆           ┆           ┆           ┆   ┆           ┆ fig/custo ┆ _model1_o ┆ stom_mod │
│           ┆           ┆           ┆           ┆   ┆           ┆ m_m…      ┆ rig…      ┆ el1_or…  │
│ model_one ┆ model_one ┆ original  ┆ standard  ┆ … ┆ 0.01372   ┆ configs/d ┆ logs/deep ┆ models/d │
│           ┆           ┆           ┆           ┆   ┆           ┆ eepnn_con ┆ nn/model_ ┆ eepnn/mo │
│           ┆           ┆           ┆           ┆   ┆           ┆ fig/model ┆ one_origi ┆ del_one_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ _tw…      ┆ nal…      ┆ origin…  │
│ Baseline  ┆ model_one ┆ original  ┆ standard  ┆ … ┆ 0.014815  ┆ configs/d ┆ logs/deep ┆ models/d │
│ model     ┆           ┆           ┆           ┆   ┆           ┆ eepnn_con ┆ nn/Baseli ┆ eepnn/Ba │
│           ┆           ┆           ┆           ┆   ┆           ┆ fig/model ┆ ne model_ ┆ seline   │
│           ┆           ┆           ┆           ┆   ┆           ┆ _on…      ┆ ori…      ┆ model_o… │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘